apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:vykHxaIXYDjTo7DxOmRkBPFIyQ==,iv:NlJnco8VdKIG9fczJxwJvLMU1Wygqo0lYgr6GxgCvWc=,tag:G+Yt/vtmtLBt+3b/q5oXmQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age153gpfdw58csvgxj3vn9ym2g3zx7mfhaldyz5uvvrfajne8htj3asjqrp7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjNWVmWHp3RVJmVjIyRStP
            ZUZKMlV4Q0N3ZVFjSnlUNUJGcVBJUEZQZ0VVCmljWTZKamxaeTVWS1JxZTBVREJO
            MENHTEFhbHRjNkI4VDE0YWN6NklKd0kKLS0tIFFvcGpzdExsYnBycGQrb1ZrOXlu
            bmVPczQwaEJKOHd3NWNiVFBBdWZxWHcKRI/itd2XqXfTYFq8HPa8J6JI2uSetv1b
            jNYR/4s5HZv/DuIsq6isDbiRQ9IBgUW1XMc4U7obSmF5kiZbdJtOHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-06T01:28:27Z"
    mac: ENC[AES256_GCM,data:lk2oxPcMySblxCGFdPT2WWVakiGTPhmrMxCanjlM4pbiR87GuiFZl7brrJyBhSigmQAX+c4lSRMowl/jX6xuAY0/5dS+FMy3/nqzHY5Sn4ajlefpJmDEzV7tcea8hk9p/KypFBfdO/4TsV/DVklpoXq4TjMjq+EchxAp4TVe0Z0=,iv:rIkL/RnhwBdOFzEaNSCyWpdSZoX24odY2ZIIGhDemUU=,tag:3ko34seqZ+gtIao6+PKODQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
