apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:yJqZYIN2JxRoB+WQRl4W6rGMM2TVBymZWOQgdxdHl4awBDjcaCA4rZPfaKHK0SabpiLCyDe6ufmTeJhL,iv:5nVOSZ5UDiPiLItQCTyMToqfPKKfWn3mHmGglD6eyFI=,tag:WZy08pVzEaVZVZu4Vqsrcw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age153gpfdw58csvgxj3vn9ym2g3zx7mfhaldyz5uvvrfajne8htj3asjqrp7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Vm1XN3owMkJTOE9DbFpB
            czVwVkgzWCs1aTUzNjljTkgvVXZsRkxXN0J3CjhDVU9tOHVocWYyd2JZaHF5QWg1
            TlYxeUduYzhGSWxMUEpTb09rRHVJTVUKLS0tIFpIaHJYcG9YSml4UTNxbUtocXB2
            SXNBUU9sT0dCU3RnS2pQVWZBOTU5TUEK9ZuXd83xtzdjl/AnFz0NnOqRHYIThgZq
            ff0uIe2th+5dW9dgHQienvfeZQJK3sABjHD18wsQ1AyUJ8gUYXe2uQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-06T01:28:27Z"
    mac: ENC[AES256_GCM,data:3vqGixVtWUvS0sY+4jC1xaPgMy88mbzKs6B8q4287xH5VnR9mwrUiDgUVtr6kiF/XmW+QT9dX3AyfF+agINZZuknxRGdDIPABJchraxCJhd+Oq+IwXZ/pXa5h/SQVRo+MjCzpUm7qx5xVuxlcw99GwRw/hnkIvhe0YHa/V55bCc=,iv:TbcKyiphAd6luVWx2f0P1w2crlXi8Ysitxi+E+q724w=,tag:o30B7+eRXlIWFA2GijWLGQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
